class Urls:
    url = 'https://stellarburgers.nomoreparties.site/'
    registration_url = f'{url}register'
    profile_url = f'{url}account/profile'
    login_url = f'{url}login'
    history_url = f'{url}account/order-history'
    forgot_password_url = f'{url}forgot-password'
    reset_password_url = f'{url}reset-password'
    feed_url = f'{url}feed'
    reg_user_api = f'{url}api/auth/register'
    del_user_api = f'{url}api/auth/user'