from selenium.webdriver.common.by import By

class MainPageLocators:
    souses = [By.XPATH, ".//h2[text()='Соусы']"]
    burger_section = [By.CLASS_NAME, ".BurgerIngredients_ingredients__1N8v2"]
    buns = [By.XPATH, ".//h2[text()='Булки']"]
    buns_logo = [By.XPATH, ".//ul[@class='BurgerIngredients_ingredients__list__2A-mT']"]
    bun_drag = [By.XPATH, ".//a[@class='BurgerIngredient_ingredient__1TVf6 ml-4 mr-4 mb-8']/p[contains(text(),'Краторная')]"]
    constructor_drop = [By.XPATH, ".//ul[@class='BurgerConstructor_basket__list__l9dp_']"]
    ingredients = [By.XPATH, ".//h2[text()='Начинки']"]
    first_bun = [By.XPATH, ".//a[@class='BurgerIngredient_ingredient__1TVf6 ml-4 mr-4 mb-8']/p[contains(text(),'Флюоресцентная')]"]
    ingredient_active = [By.XPATH, ".//section[@class='Modal_modal_opened__3ISw4 Modal_modal__P3_V5']"]
    ingredient_hidden = [By.XPATH, ".//section[@class='Modal_modal__P3_V5']//div[@class='Modal_modal__contentBox__sCy8X pt-10 pb-15']"]
    ingredient_details = [By.XPATH, ".//h2[text()='Детали ингредиента']"]
    ingredient_close = [By.XPATH, ".//section[@class='Modal_modal_opened__3ISw4 Modal_modal__P3_V5']//button"]
    enter_button = [By.XPATH, ".//button[text()='Войти в аккаунт']"]
    personal_account = [By.XPATH, ".//p[text()='Личный Кабинет']"]
    constractor_icon = [By.XPATH, ".//p[text()='Конструктор']"]
    create_order = [By.XPATH, ".//button[text()='Оформить заказ']"]
    feed_orders = [By.XPATH, ".//p[text()='Лента Заказов']"]
    counter = [By.XPATH, ".//p[contains(text(),'Краторная')]/parent::*/div/p[@class='counter_counter__num__3nue1' and contains(text(),'')]"]
    create_order_modal = [By.XPATH, ".//h2[@class='Modal_modal__title_shadow__3ikwq Modal_modal__title__2L34m text text_type_digits-large mb-8']"]
    close_order_modal = [By.XPATH, ".//button[@type='button']"]